"""Add task_number column to tasks

Revision ID: 7f6c1ae3e3ed
Revises: c90fd993ef96
Create Date: 2026-02-13 03:32:53.949960

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers
revision = '7f6c1ae3e3ed'
down_revision = 'c90fd993ef96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_number')
    # ### end Alembic commands ###